config/routes.rb
LoyalityCards::Application.routes.draw do

  resources :addresses

  resources :orders

  resources :order_items

  resources :cards

  match '/auth/:provider/callback', to: 'sessions#create'
  match "/login" => redirect("/auth/twitter"), as: :login
  match "/logout" => "sessions#destroy", as: :logout

  resources :orders do
    member do
      put :purchase
    end
  end

end

app/models/address.rb
class Address < ActiveRecord::Base
  attr_accessible :line1, :line2, :city, :state, :zip, :user_id
  belongs_to :user
  has_many :orders

  def to_s
   line1
  end
end

app/models/card.rb
class Card < ActiveRecord::Base
  attr_accessible :title, :price, :description, :image_url, :stock
  has_many :order_items
  validates :stock, :numericality => { :only_integer => true, :greater_than_or_equal_to => 0 }
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :user, :customer_id, :status, :address_id
  has_many :order_items, dependent: :destroy
  belongs_to :user, foreign_key: :customer_id
  belongs_to :address

end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  attr_accessible :card_id, :order_id, :quantity
  belongs_to :order
  belongs_to :card

  def subtotal
    quantity * card.price
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :provider, :uid
  has_many :orders
  has_many :addresses

  def self.find_or_create_by_auth(auth_data)
    find_or_create_by_provider_and_uid(auth_data["provider"], auth_data["uid"],
                                       name: auth_data["info"]["name"])
  end
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  def index
    @addresses = Address.all
  end

  def show
    @address = Address.find(params[:id])
  end

  def new
    @address = Address.new
  end

  def create
    @address = Address.new(params[:address])
    if @address.save
      redirect_to @address, :notice => "Successfully created address."
    else
      render :action => 'new'
    end
  end

  def edit
    @address = Address.find(params[:id])
  end

  def update
    @address = Address.find(params[:id])
    if @address.update_attributes(params[:address])
      redirect_to @address, :notice  => "Successfully updated address."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @address = Address.find(params[:id])
    @address.destroy
    redirect_to addresses_url, :notice => "Successfully destroyed address."
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user

  def load_order
    begin
      @order = Order.find(session[:order_id])
    rescue ActiveRecord::RecordNotFound
      if current_user
        @order = current_user.orders.create(status: "unsubmitted")
      else
        @order = Order.create(status: "unsubmitted")
      end
      session[:order_id] = @order.id
    end
  end

  private
    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_filter :load_order

  def index
    @cards = Card.all
  end

  def show
    @card = Card.find(params[:id])
  end

  def new
    @card = Card.new
  end

  def create
    @card = Card.new(params[:card])
    if @card.save
      redirect_to @card, :notice => "Successfully created card."
    else
      render :action => 'new'
    end
  end

  def edit
    @card = Card.find(params[:id])
  end

  def update
    @card = Card.find(params[:id])
    if @card.update_attributes(params[:card])
      redirect_to @card, :notice  => "Successfully updated card."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @card = Card.find(params[:id])
    @card.destroy
    redirect_to cards_url, :notice => "Successfully destroyed card."
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  before_filter :load_order

  def index
    @order_items = OrderItem.all
  end

  def show
    @order_item = OrderItem.find(params[:id])
  end

  def new
    @order_item = OrderItem.new
  end

  def create
    @order_item = @order.order_items.find_or_initialize_by_card_id(params[:card_id])
    if @order_item.save
      redirect_to @order_item, :notice => "Successfully created order item."
    else
      render :action => 'new'
    end
  end

  def edit
    @order_item = OrderItem.find(params[:id])
  end

  def update
    @order_item = OrderItem.find(params[:id])
    if @order_item.update_attributes(params[:order_item])
      redirect_to @order_item, :notice  => "Successfully updated order item."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @order_item = OrderItem.find(params[:id])
    @order_item.destroy
    redirect_to order_items_url, :notice => "Successfully destroyed order item."
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(params[:order])
    if @order.save
      redirect_to @order, :notice => "Successfully created order."
    else
      render :action => 'new'
    end
  end

  def edit
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    if @order.update_attributes(params[:order])
      redirect_to @order, :notice  => "Successfully updated order."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    redirect_to orders_url, :notice => "Successfully destroyed order."
  end

  def purchase
    # Find the order
    # Set the address_id
    # Change the status to "submitted"
    # Save it
    # Remove the order_id from the session so they can't edit it
    # Display a thank you page with an order summary
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.find_or_create_by_auth(request.env["omniauth.auth"])
    session[:user_id] = @user.id
    load_order
    @order.update_attributes(user: @user)
    redirect_to products_path, notice: "Logged in as #{@user.name}"
  end

  def destroy
    session[:user_id] = nil
    session[:order_id] = nil
    redirect_to root_path
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
  def print_price(price)
    number_to_currency(price, :unit => "&euro;", :separator => ",", :delimiter => "", :format => "%n %u")
  end

  def print_stock(stock)
    if stock > 0
      "In stock (#{stock})"
    else
      "Out of stock"
    end
  end
end

app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/addresses/_form.html.erb
<%= form_for @address do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :line1 %><br />
    <%= f.text_field :line1 %>
  </p>
  <p>
    <%= f.label :line2 %><br />
    <%= f.text_field :line2 %>
  </p>
  <p>
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </p>
  <p>
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </p>
  <p>
    <%= f.label :zip %><br />
    <%= f.text_field :zip %>
  </p>
  <p>
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/addresses/edit.html.erb
<% title "Edit Address" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @address %> |
  <%= link_to "View All", addresses_path %>
</p>

app/views/addresses/index.html.erb
<% title "Addresses" %>

<table>
  <tr>
    <th>Line1</th>
    <th>Line2</th>
    <th>City</th>
    <th>State</th>
    <th>Zip</th>
    <th>User</th>
  </tr>
  <% for address in @addresses %>
    <tr>
      <td><%= address.line1 %></td>
      <td><%= address.line2 %></td>
      <td><%= address.city %></td>
      <td><%= address.state %></td>
      <td><%= address.zip %></td>
      <td><%= address.user_id %></td>
      <td><%= link_to "Show", address %></td>
      <td><%= link_to "Edit", edit_address_path(address) %></td>
      <td><%= link_to "Destroy", address, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Address", new_address_path %></p>

app/views/addresses/new.html.erb
<% title "New Address" %>

<%= render 'form' %>

<p><%= link_to "Back to List", addresses_path %></p>

app/views/addresses/show.html.erb
<% title "Address" %>

<p>
  <strong>Line1:</strong>
  <%= @address.line1 %>
</p>
<p>
  <strong>Line2:</strong>
  <%= @address.line2 %>
</p>
<p>
  <strong>City:</strong>
  <%= @address.city %>
</p>
<p>
  <strong>State:</strong>
  <%= @address.state %>
</p>
<p>
  <strong>Zip:</strong>
  <%= @address.zip %>
</p>
<p>
  <strong>User:</strong>
  <%= @address.user_id %>
</p>

<p>
  <%= link_to "Edit", edit_address_path(@address) %> |
  <%= link_to "Destroy", @address, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", addresses_path %>
</p>

app/views/cards/_form.html.erb
<%= form_for @card do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </p>
    <p>
      <%= f.label :stock %><br />
      <%= f.text_field :stock %>
    </p>
  <p><%= f.submit %></p>
<% end %>

app/views/cards/edit.html.erb
<% title "Edit Card" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @card %> |
  <%= link_to "View All", cards_path %>
</p>

app/views/cards/index.html.erb
<% title "Cards" %>

<table>
  <tr>
    <th>Title</th>
    <th>Price</th>
    <th>Description</th>
    <th>Image Url</th>
    <th>Stock</th>
    <th>Buy</th>
  </tr>
  <% for card in @cards %>
    <tr>
      <td><%= card.title %></td>
      <td><%= print_price(card.price) %></td>
      <td><%= card.description %></td>
      <td><%= card.image_url %></td>
      <td><%= print_stock(card.stock) %></td>
      <td><%= button_to "Add to Cart", order_items_path(card_id: card.id) %></td>
      <td><%= link_to "Show", card %></td>
      <td><%= link_to "Edit", edit_card_path(card) %></td>
      <td><%= link_to "Destroy", card, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "Create a New Card", new_card_path, id: "new_card" %></p>

<p>
  Item Count: <%= @order.order_items.count %>
</p>

app/views/cards/new.html.erb
<% title "New Card" %>

<%= render 'form' %>

<p><%= link_to "Back to List", cards_path %></p>

app/views/cards/show.html.erb
<% title "Card" %>

<p>
  <strong>Title:</strong>
  <%= @card.title %>
</p>
<p>
  <strong>Price:</strong>
  <%= @card.price %>
</p>
<p>
  <strong>Description:</strong>
  <%= @card.description %>
</p>
<p>
  <strong>Image Url:</strong>
  <%= @card.image_url %>
</p>

<p>
  <%= link_to "Edit", edit_card_path(@card) %> |
  <%= link_to "Destroy", @card, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", cards_path %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= controller.action_name %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if flash[:notice] %>
    <p class='notice'><%= flash[:notice] %></p>
<% end %>
<div id="account">
  <% if current_user %>
      <span>Welcome, <%= current_user.name %></span>
      <%= link_to "logout", logout_path, id: "login" %>
  <% else %>
      <%= link_to "login", login_path, id: "logout" %>
  <% end %>
</div>
<div class="wrapper">
  <div class="header">
    <h1>FoodWorks</h1>
    <p>Your Online Grocery</p>
  </div>

  <div class="sidebar">
    (sidebar)
  </div>

  <div class="main">
    <%= yield %>
  </div>

  <div class="footer">
    FoodWorks Online Grocery<br/>
    A Rails Jumpstart Project
  </div>
</div>
</body>
</html>

app/views/order_items/_form.html.erb
<%= form_for @order_item do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :card_id %><br />
    <%= f.number_field :card_id %>
  </p>
  <p>
    <%= f.label :order_id %><br />
    <%= f.number_field :order_id %>
  </p>
  <p>
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/order_items/edit.html.erb
<% title "Edit Order Item" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @order_item %> |
  <%= link_to "View All", order_items_path %>
</p>

app/views/order_items/index.html.erb
<% title "Order Items" %>

<table>
  <tr>
    <th>Card</th>
    <th>Order</th>
    <th>Quantity</th>
  </tr>
  <% for order_item in @order_items %>
    <tr>
      <td><%= order_item.card_id %></td>
      <td><%= order_item.order_id %></td>
      <td><%= order_item.quantity %></td>
      <td><%= link_to "Show", order_item %></td>
      <td><%= link_to "Edit", edit_order_item_path(order_item) %></td>
      <td><%= link_to "Destroy", order_item, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Order Item", new_order_item_path %></p>

app/views/order_items/new.html.erb
<% title "New Order Item" %>

<%= render 'form' %>

<p><%= link_to "Back to List", order_items_path %></p>

app/views/order_items/show.html.erb
<% title "Order Item" %>

<p>
  <strong>Card:</strong>
  <%= @order_item.card_id %>
</p>
<p>
  <strong>Order:</strong>
  <%= @order_item.order_id %>
</p>
<p>
  <strong>Quantity:</strong>
  <%= @order_item.quantity %>
</p>

<p>
  <%= link_to "Edit", edit_order_item_path(@order_item) %> |
  <%= link_to "Destroy", @order_item, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All", order_items_path %>
</p>

app/views/orders/_form.html.erb
<%= form_for @order do |f| %>
  <%= f.error_messages %>
  <p>
    <%= f.label :customer_id %><br />
    <%= f.number_field :customer_id %>
  </p>
  <p>
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/orders/edit.html.erb
<% title "Edit Order" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @order %> |
  <%= link_to "View All", orders_path %>
</p>

app/views/orders/index.html.erb
<% title "Orders" %>

<table>
  <tr>
    <th>Customer</th>
    <th>Status</th>
  </tr>
  <% for order in @orders %>
    <tr>
      <td><%= order.customer_id %></td>
      <td><%= order.status %></td>
      <td><%= link_to "Show", order %></td>
      <td><%= link_to "Edit", edit_order_path(order) %></td>
      <td><%= link_to "Destroy", order, :confirm => 'Are you sure?', :method => :delete %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to "New Order", new_order_path %></p>

app/views/orders/new.html.erb
<% title "New Order" %>

<%= render 'form' %>

<p><%= link_to "Back to List", orders_path %></p>

app/views/orders/show.html.erb
<h1>Your Order</h1>

<table>
  <tr>
    <th>Customer</th>
    <td><%= @order.user.name if @order.user %></td>
  </tr>
  <tr>
    <th>Status:</th>
    <td><%= @order.status %></td>
  </tr>
  <tr>
    <th>Items:</th>
    <td><%= @order.order_items.count %></td>
  </tr>
  <tr>
    <th>Items</th>
    <th>Title</th>
    <th>Quantity</th>
    <th>Unit Price</th>
    <th>Subtotal</th>
  </tr>
  <% @order.order_items.each do |item| %>
      <tr>

        <td><%= item.card.title %></td>
        <td><%= link_to item.quantity, edit_order_item_path(item) %></td>
        <td><%= item.card.price %></td>
        <td><%= print_price item.subtotal %></td>


      </tr>
  <% end %>
  <tr>
  <tr>
    <th>Shipping To:</th>
    <td>
      <%= form_for @order, url: purchase_order_path(@order), method: :put do |f| %>
          <%= f.select :address_id, current_user.addresses.collect{|a| [a.to_s, a.id]} %>
          <%= f.submit "Submit Order" %>
    <% end %>
          </td>
  </tr>
  </tr>

  <%= link_to "Empty Cart", @order, confirm: 'Are you sure?', method: :delete %>
</table>